language: c
script: asdf plugin-test minishift https://github.com/bartoszmajsak/asdf-minishift.git
before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh
os:
  - linux
  - osx
  - windows
